GET http://localhost:5157/pokemons

###
GET http://localhost:5157/pokemons/5

###
POST http://localhost:5157/pokemons
Content-Type: application/json

{
    "name": "Lucario2",
    "type": "Fighting/Steel",
    "hp": 70,
    "attack": 90,
    "defense": 70,
    "imageUrl": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/448.png"
}

###
PUT http://localhost:5157/pokemons/7
Content-Type: application/json

{
    "name": "Lucario3",
    "type": "Fighting/Running",
    "hp": 78,
    "attack": 120,
    "defense": 90,
    "imageUrl": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/448.png"
}

###
DELETE http://localhost:5157/pokemons/3

